// Encodes a binary .fbx into an ES module exporting a data URI, because webpack
// cannot inline .fbx directly (no mimetype in its database) and a playable must
// build to a single self-contained HTML file.
//   node scripts_fbx2base64.mjs assets/models/B_Boat.fbx
import { readFileSync, writeFileSync } from 'fs';

const src = process.argv[2];
if (!src) { console.error('usage: node scripts_fbx2base64.mjs <file.fbx>'); process.exit(1); }
const b64 = readFileSync(src).toString('base64');
const out = `${src}.js`;
writeFileSync(out,
`// GENERATED by scripts_fbx2base64.mjs from ${src.split('/').pop()} — do not edit.
// Regenerate after replacing the model:
//   node scripts_fbx2base64.mjs ${src}
export default 'data:application/octet-stream;base64,${b64}';
`);
console.log(`${out}  (${(b64.length/1024).toFixed(0)} KB base64 from ${(readFileSync(src).length/1024).toFixed(0)} KB fbx)`);
